FROM nginx:1.27-alpine

COPY pasztar/frontend/nginx.conf /etc/nginx/templates/default.conf.template
COPY pasztar/frontend/index.html pasztar/frontend/setup.html /usr/share/nginx/html/
COPY pasztar/frontend/assets /usr/share/nginx/html/assets
COPY pasztar/frontend/static /usr/share/nginx/html/static
