FROM python:3.12-slim

ENV POETRY_VERSION=1.8.4 \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONUNBUFFERED=1

WORKDIR /srv/pasztar/backend

RUN pip install "poetry==$POETRY_VERSION"

COPY pasztar/backend/pyproject.toml pasztar/backend/poetry.lock ./
COPY pasztar/backend/src ./src
COPY pasztar/backend/migrations ./migrations
COPY pasztar/backend/alembic.ini pasztar/backend/entrypoint.sh ./

RUN poetry install --only main --no-interaction --no-ansi
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
